name: AliWasHere
favicon: null
layout_spectrum: 0.2939068
typography_spectrum: 0.3172043
title: AliWasHere
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#505c82'
    - '#000034'
    - '#263556'
    - '#8a8cff'
    - '#0030a8'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
